/**
 * Default Test Plan Template
 * 
 * This is a fallback template used when no PDF template is uploaded.
 * It's inserted into the database during initialization if no templates exist.
 */

export const DEFAULT_TEMPLATE_CONTENT = `# Test Plan

## 1. Overview

### 1.1 Purpose
Describe the purpose of this test plan.

### 1.2 Scope
Define what will be tested and what will not be tested.

### 1.3 References
- JIRA Ticket: {{ticket.key}}
- Summary: {{ticket.summary}}

---

## 2. Test Items

### 2.1 Features to be Tested
List the features/requirements to be tested based on acceptance criteria.

{{ticket.acceptanceCriteria}}

### 2.2 Features Not to be Tested
List features explicitly excluded from testing.

---

## 3. Test Approach

### 3.1 Test Types
- **Functional Testing**: Verify functionality works as expected
- **Integration Testing**: Test interaction between components
- **Regression Testing**: Ensure existing functionality still works
- **User Acceptance Testing**: Validate against user requirements

### 3.2 Test Techniques
- Black-box testing
- Boundary value analysis
- Equivalence partitioning
- Exploratory testing

---

## 4. Test Environment

### 4.1 Hardware Requirements
List required hardware configurations.

### 4.2 Software Requirements
List required software and versions.

### 4.3 Test Data
Describe test data requirements.

---

## 5. Test Cases

### 5.1 Positive Test Cases

| ID | Test Case | Steps | Expected Result | Priority |
|----|-----------|-------|-----------------|----------|
| TC001 | Happy path scenario | 1. Step one<br>2. Step two | Expected outcome | High |

### 5.2 Negative Test Cases

| ID | Test Case | Steps | Expected Result | Priority |
|----|-----------|-------|-----------------|----------|
| TC002 | Invalid input handling | 1. Enter invalid data<br>2. Submit | Error message displayed | Medium |

### 5.3 Edge Cases

| ID | Test Case | Steps | Expected Result | Priority |
|----|-----------|-------|-----------------|----------|
| TC003 | Boundary condition | 1. Test at limit<br>2. Verify behavior | System handles gracefully | Medium |

---

## 6. Test Schedule

| Phase | Start Date | End Date | Duration |
|-------|------------|----------|----------|
| Test Planning | TBD | TBD | X days |
| Test Design | TBD | TBD | X days |
| Test Execution | TBD | TBD | X days |
| Test Reporting | TBD | TBD | X days |

---

## 7. Entry and Exit Criteria

### 7.1 Entry Criteria
- Requirements are approved and baselined
- Test environment is ready
- Test data is prepared
- Test cases are reviewed and approved

### 7.2 Exit Criteria
- All test cases executed
- Critical and high defects resolved
- Test coverage meets target (e.g., 90%)
- Test summary report approved

---

## 8. Risks and Mitigation

| Risk | Impact | Probability | Mitigation Strategy |
|------|--------|-------------|---------------------|
| Scope changes | High | Medium | Regular scope reviews |
| Environment issues | Medium | High | Early environment setup |
| Resource unavailability | High | Low | Backup resources identified |

---

## 9. Roles and Responsibilities

| Role | Name | Responsibilities |
|------|------|------------------|
| Test Lead | TBD | Overall test management |
| Test Engineers | TBD | Test case design and execution |
| Developers | TBD | Defect fixes and support |

---

## 10. Deliverables

- Test Plan Document (this document)
- Test Cases
- Test Data
- Test Execution Reports
- Defect Reports
- Test Summary Report

---

## 11. Approval

| Role | Name | Signature | Date |
|------|------|-----------|------|
| Test Lead | | | |
| Project Manager | | | |
| Product Owner | | | |

---

*Generated by Intelligent Test Plan Generator*
*Based on JIRA Ticket: {{ticket.key}} - {{ticket.summary}}*
`;

export default DEFAULT_TEMPLATE_CONTENT;
